version: '3'

volumes:
  # Crowd server stroage
  crowd-data:
  # Bitbucket server stroage
  bitbucket-data:

services:

  ldap:
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: "dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "password"
    security_opt:
      # Disable SElinux for volume mounts (since we're using a host mount)
      - "label=disable"
    volumes:
      # Helper scripts
      - "./ldap-init:/opt/ldap-init:ro"
    ports:
      - 127.0.0.1:1389:389
      - 127.0.0.1:1636:633
    # We define a healthcheck so the container doing the init knows when LDAP is online
    healthcheck:
      test: ["CMD", "ldapwhoami", "-D", "cn=admin,dc=example,dc=com", "-w", "password", "-H", "ldap://127.0.0.1:389"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s

  # TODO: Look for a native mechanism within the server to do this on startup
  # (which should be faster than waiting for container to be ready)
  ldap-init:
    # Wait for LDAP to be online
    depends_on:
      ldap:
        condition: service_healthy
    image: osixia/openldap:latest
    volumes:
      # Helper scripts
      - "./ldap-init:/opt/ldap-init:ro"
    entrypoint: /opt/ldap-init/entrypoint-ldap-init.sh

  ldap-ui:
    image: osixia/phpldapadmin:latest
    ports:
      - 127.0.0.1:8443:443
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"

  crowd:
    image: atlassian/crowd:latest
    environment:
      CROWD_DB_URL: jdbc:postgresql://crowd-db:5432/crowd
      CROWD_DB_USER: postgres
      CROWD_DB_PASSWORD: password
    volumes:
      - crowd-data:/var/atlassian/application-data/crowd
    ports:
      - 127.0.0.1:8095:8095

  bibucket:
    image: atlassian/bitbucket:latest
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    ports:
      - 127.0.0.1:7990:7990
      - 127.0.0.1:7999:7999

